graphs:
	pdflatex graphdiff_6.tex
	pdf2svg graphdiff_6.pdf graphdiff_6.svg
	pdf2svg graphdiff_9.pdf graphdiff_9.svg
	pdf2svg graphdiff_14.pdf graphdiff_14.svg
	rm graphdiff_6.pdf graphdiff_9.pdf graphdiff_14.pdf
